package io.gomob.feature.message

data class ContactProfileUi(
    val id: String,
    val name: String,
    val initials: String,
    val roleTitle: String,
    val specialty: String,
    val employeeId: String,
    val availabilityText: String,
    val organization: String,
    val online: Boolean,
    val peerUserId: Long?,
) {
    val avatarSeed: String get() = "contact-$id-$name"
}

internal fun localContactProfiles(): List<ContactProfileUi> = listOf(
    ContactProfileUi(
        id = "station-zhou",
        name = "周科",
        initials = "周",
        roleTitle = "OBD 主审",
        specialty = "OBD 排放诊断、故障码复核",
        employeeId = "ZAA01",
        availabilityText = "在线",
        organization = "杭州西湖检测站",
        online = true,
        peerUserId = null,
    ),
    ContactProfileUi(
        id = "station-wu",
        name = "吴风",
        initials = "吴",
        roleTitle = "外观件专家",
        specialty = "车身外观件、结构件损伤复核",
        employeeId = "ZAA02",
        availabilityText = "在线",
        organization = "杭州西湖检测站",
        online = true,
        peerUserId = null,
    ),
    ContactProfileUi(
        id = "station-liu",
        name = "刘冶",
        initials = "刘",
        roleTitle = "VIN 拓印",
        specialty = "VIN 拓印、车架号一致性核验",
        employeeId = "ZAA03",
        availabilityText = "忙碌",
        organization = "杭州西湖检测站",
        online = false,
        peerUserId = null,
    ),
    ContactProfileUi(
        id = "station-jiang",
        name = "江庆宇",
        initials = "江",
        roleTitle = "查验员",
        specialty = "车辆查验、资料核对、现场协作",
        employeeId = "ZAA04",
        availabilityText = "忙碌",
        organization = "杭州西湖检测站",
        online = false,
        peerUserId = null,
    ),
    ContactProfileUi(
        id = "station-shen",
        name = "沈海明",
        initials = "沈",
        roleTitle = "查验员",
        specialty = "车辆查验、站内复核、异常记录",
        employeeId = "ZAA0120230001",
        availabilityText = "在线",
        organization = "杭州西湖检测站",
        online = true,
        peerUserId = null,
    ),
    ContactProfileUi(
        id = "supervision-review",
        name = "省所复核",
        initials = "省",
        roleTitle = "监管复核",
        specialty = "监管复核、争议查验、流程确认",
        employeeId = "REG01",
        availabilityText = "在线",
        organization = "浙江省车管所",
        online = true,
        peerUserId = null,
    ),
    ContactProfileUi(
        id = "supervision-duty",
        name = "值班督导",
        initials = "督",
        roleTitle = "异常督办",
        specialty = "异常督办、跨站协同、时效跟进",
        employeeId = "REG02",
        availabilityText = "忙碌",
        organization = "浙江省车管所",
        online = false,
        peerUserId = null,
    ),
)

internal fun HelpExpertRowUi.toContactProfileUi(): ContactProfileUi = ContactProfileUi(
    id = "expert-$userId",
    name = name,
    initials = initials,
    roleTitle = roleTitle,
    specialty = specialty,
    employeeId = employeeId,
    availabilityText = availabilityText,
    organization = "外部专家 · 协作池",
    online = availabilityText == "可发消息",
    peerUserId = userId,
)
